# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# local server (for "jekyll serve") will be localhost:{PORT number below}
port: 7000

# TODO change title
title: Brightcove Engage
email: training@brightcove.com
# TODO change description
description: >- # this means to ignore newlines until "baseurl:"
  Brightcove Campaign provides a set of tools to help enrich your corporate communications with video content.
# baseurl: "" # the subpath of your site, e.g. /blog
# TODO change description
site_url: "https://engage.support.brightcove.com"
site_domain: "engage.support.brightcove.com"

# Build settings
# theme: minima

#TODO change product
product: Brightcove Engage
color: rgb(51, 51, 51)
product_color: rgb(243, 148, 36)
product_icon: "engage-logo.svg"
search_id: "017969773216783359937:6sd3di5mwuw"
feedbackify_id: "14986"
bing_custom_config_id: "f8f799ba-ae88-4fe0-99d0-baf312dc3ab9"
defaults:
  - 
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

# plugins
plugins:
  - jekyll-last-modified-at

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
